# -*- coding: utf-8 -*-
"""train.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1jvQ-UDMi1ClztuitEhgduyTXKBI8pGx2
"""

# CELL 1 — Install dependencies
# ──────────────────────────────────────────────────────────────
!pip install -q timm

# CELL 2 — Mount Google Drive (run if dataset is in Drive)
# ──────────────────────────────────────────────────────────────
from google.colab import drive
drive.mount('/content/drive')

import os

# See top-level folders in MyDrive
if os.path.exists('/content/drive/MyDrive'):
    for item in os.listdir("/content/drive/MyDrive"):
        print(item)
else:
    print("Error: /content/drive/MyDrive not found. Listing contents of /content/drive:")
    if os.path.exists('/content/drive'):
        for item in os.listdir("/content/drive"):
            print(item)
    else:
        print("/content/drive itself is not found. Please ensure Google Drive is mounted correctly.")

# Replace 'YourFolderName' with what you see above
for item in os.listdir("/content/drive/MyDrive/EuroSAT_Project"):
    print(item)

# CELL 3 — Copy dataset locally for faster I/O (recommended)
# ──────────────────────────────────────────────────────────────
!cp -r "/content/drive/MyDrive/EuroSAT_Project/EuroSAT" /content/
!cp "/content/drive/MyDrive/EuroSAT_Project/train.csv"      /content/
!cp "/content/drive/MyDrive/EuroSAT_Project/validation.csv" /content/
!cp "/content/drive/MyDrive/EuroSAT_Project/test.csv"       /content/

"""### Debugging Dataset Copy

Let's verify the contents of the `EuroSAT` directory on your Google Drive and the copied directory in `/content/` to understand why the files are not being found. We'll list the subdirectories, which correspond to the classes, and then explicitly check for a file that caused an error.
"""

print("Contents of original EuroSAT directory on Google Drive:")
original_path = "/content/drive/MyDrive/EuroSAT_Project/EuroSAT"
if os.path.exists(original_path):
    for item in os.listdir(original_path):
        print(item)
else:
    print(f"Error: {original_path} not found.")

print("\nContents of copied EuroSAT directory in /content/:")
copied_path = "/content/EuroSAT"
if os.path.exists(copied_path):
    for item in os.listdir(copied_path):
        print(item)
else:
    print(f"Error: {copied_path} not found.")

print("\nChecking for problematic file '/content/EuroSAT/SeaLake/SeaLake_2183.jpg':")
problematic_file = "/content/EuroSAT/SeaLake/SeaLake_2183.jpg"
if os.path.exists(problematic_file):
    print(f"✅ File found: {problematic_file}")
else:
    print(f"❌ File NOT found: {problematic_file}")

print("\nChecking for problematic file in original Google Drive location:")
original_problematic_file = "/content/drive/MyDrive/EuroSAT_Project/EuroSAT/SeaLake/SeaLake_2183.jpg"
if os.path.exists(original_problematic_file):
    print(f"✅ File found: {original_problematic_file}")
else:
    print(f"❌ File NOT found: {original_problematic_file}")

# ╔═══════════════════════════════════════════════╗
# ║  CELL 4 — Imports & Configuration                           ║
# ╚═══════════════════════════════════════════════╝
import os
import time
import numpy as np
import pandas as pd
from PIL import Image

import torch
import torch.nn as nn
import torch.optim as optim
from torch.utils.data import Dataset, DataLoader
from torchvision import transforms, models

from sklearn.metrics import accuracy_score, f1_score, classification_report
from tqdm.auto import tqdm

# ══ Device ════════════════════════════════════════════
DEVICE = torch.device("cuda" if torch.cuda.is_available() else "cpu")
print(f"✅ Using device: {DEVICE}")
if DEVICE.type == "cuda":
    print(f"   GPU: {torch.cuda.get_device_name(0)}")

# ══ Paths — EDIT THESE to match your setup ══════════════════
DATASET_DIR   = "/content/EuroSAT"       # root folder with class sub-folders
TRAIN_CSV     = "/content/train.csv"
VAL_CSV       = "/content/validation.csv"
TEST_CSV      = "/content/test.csv"
OUTPUT_CSV    = "/content/submission.csv"
CHECKPOINT    = "/content/best_model.pth"

# ══ Hyperparameters ═════════════════════════════════════
IMG_SIZE      = 224
BATCH_SIZE    = 64
NUM_WORKERS   = 2
NUM_EPOCHS    = 10
LR            = 3e-4
LR_DECAY      = 0.1      # factor for scheduler
PATIENCE      = 3         # early stopping
NUM_CLASSES   = 6 # Updated from 10 to 6 as only 6 classes are present in the dataset
SEED          = 42

torch.manual_seed(SEED)
np.random.seed(SEED)

# ╔═══════════════════════════════════════════════╗
# ║  CELL 5 — Dataset & Transforms                              ║
# ╚═══════════════════════════════════════════════╝

# ImageNet stats (used because we load pretrained weights)
MEAN = [0.485, 0.456, 0.406]
STD  = [0.229, 0.224, 0.225]

train_transforms = transforms.Compose([
    transforms.Resize((IMG_SIZE, IMG_SIZE)),
    transforms.RandomHorizontalFlip(),
    transforms.RandomVerticalFlip(),
    transforms.RandomRotation(15),
    transforms.ColorJitter(brightness=0.2, contrast=0.2, saturation=0.2),
    transforms.ToTensor(),
    transforms.Normalize(MEAN, STD),
])

val_transforms = transforms.Compose([
    transforms.Resize((IMG_SIZE, IMG_SIZE)),
    transforms.ToTensor(),
    transforms.Normalize(MEAN, STD),
])


class EuroSATDataset(Dataset):
    """
    Reads a CSV with columns:
        image_id  — filename or relative path  (e.g. AnnualCrop/AnnualCrop_00001.jpg)
        label     — integer class index (absent in test set)

    Set `has_labels=False` for the test split.
    """

    def __init__(self, csv_path, dataset_dir, transform=None, has_labels=True):
        self.df          = pd.read_csv(csv_path)
        self.dataset_dir = dataset_dir
        self.transform   = transform
        self.has_labels  = has_labels

        # ══ normalise column names ═════════════════════
        self.df.columns = [c.strip().lower() for c in self.df.columns]

        # accept either 'image_id' or 'filename'
        if "image_id" in self.df.columns:
            self.img_col = "image_id"
        elif "filename" in self.df.columns:
            self.img_col = "filename"
        else:
            raise ValueError(f"CSV must have 'image_id' or 'filename' column. Found: {list(self.df.columns)}")

        # Filter out missing classes based on actual directories present
        actual_class_dirs = [d for d in os.listdir(dataset_dir) if os.path.isdir(os.path.join(dataset_dir, d))]
        self.df = self.df[self.df[self.img_col].apply(lambda x: x.split('/')[0] in actual_class_dirs)]

        # Further filter out rows where the image file itself does not exist
        def check_file_exists(img_name):
            img_path = os.path.join(self.dataset_dir, img_name)
            if os.path.exists(img_path):
                return True
            # Fallback: if path doesn't exist AND img_name doesn't already end with .jpg,
            # try adding .jpg extension. (This logic is also in __getitem__)
            if not img_name.lower().endswith(".jpg"):
                if os.path.exists(img_path + ".jpg"):
                    return True
            return False

        initial_len = len(self.df)
        self.df = self.df[self.df[self.img_col].apply(check_file_exists)]
        if len(self.df) < initial_len:
            print(f"Warning: Removed {initial_len - len(self.df)} entries from the dataset because image files were not found on disk.")

        self.df = self.df.reset_index(drop=True)

        if has_labels:
            if "label" not in self.df.columns:
                raise ValueError("Train/val CSV must have a 'label' column.")
            self.labels = self.df["label"].values
        else:
            self.labels = None

        self.image_ids = self.df[self.img_col].values

    def __len__(self):
        return len(self.df)

    def __getitem__(self, idx):
        img_name = self.image_ids[idx]
        img_path = os.path.join(self.dataset_dir, img_name)

        # Fallback: if path doesn't exist AND img_name doesn't already end with .jpg,
        # try adding .jpg extension.
        if not os.path.exists(img_path) and not img_name.lower().endswith(".jpg"):
            img_path = img_path + ".jpg"

        image = Image.open(img_path).convert("RGB")

        if self.transform:
            image = self.transform(image)

        if self.has_labels:
            return image, int(self.labels[idx])
        else:
            return image, img_name   # return id so we can build submission


# ══ Build datasets ══════════════════════════════
train_dataset = EuroSATDataset(TRAIN_CSV,  DATASET_DIR, train_transforms, has_labels=True)
val_dataset   = EuroSATDataset(VAL_CSV,    DATASET_DIR, val_transforms,   has_labels=True)
test_dataset  = EuroSATDataset(TEST_CSV,   DATASET_DIR, val_transforms,   has_labels=False)

# ══ Build loaders ══════════════════════════════════
train_loader = DataLoader(train_dataset, batch_size=BATCH_SIZE, shuffle=True,
                          num_workers=NUM_WORKERS, pin_memory=True)
val_loader   = DataLoader(val_dataset,   batch_size=BATCH_SIZE, shuffle=False,
                          num_workers=NUM_WORKERS, pin_memory=True)
test_loader  = DataLoader(test_dataset,  batch_size=BATCH_SIZE, shuffle=False,
                          num_workers=NUM_WORKERS, pin_memory=True)

print(f"✅ Train: {len(train_dataset)} | Val: {len(val_dataset)} | Test: {len(test_dataset)}")

# ╔══════════════════════════════════════════════════════════════╗
# ║  CELL 6 — Model (EfficientNet-B0 with custom head)          ║
# ╚══════════════════════════════════════════════════════════════╝

def build_model(num_classes=NUM_CLASSES, freeze_backbone=False):
    """
    EfficientNet-B0 pretrained on ImageNet.
    Replaces the classifier head for num_classes outputs.
    """
    model = models.efficientnet_b0(weights=models.EfficientNet_B0_Weights.DEFAULT)

    if freeze_backbone:
        for param in model.features.parameters():
            param.requires_grad = False

    # Replace classifier
    in_features = model.classifier[1].in_features
    model.classifier = nn.Sequential(
        nn.Dropout(p=0.3, inplace=True),
        nn.Linear(in_features, num_classes),
    )

    return model.to(DEVICE)


model = build_model()
print("✅ EfficientNet-B0 loaded with pretrained ImageNet weights.")
total_params     = sum(p.numel() for p in model.parameters())
trainable_params = sum(p.numel() for p in model.parameters() if p.requires_grad)
print(f"   Total params: {total_params:,}  |  Trainable: {trainable_params:,}")

# ╔══════════════════════════════════════════════════════════════╗
# ║  CELL 7 — Loss, Optimizer, Scheduler                        ║
# ╚══════════════════════════════════════════════════════════════╝

criterion = nn.CrossEntropyLoss(label_smoothing=0.1)

optimizer = optim.Adam(model.parameters(), lr=LR, weight_decay=1e-4)

# Reduce LR by LR_DECAY when val accuracy stops improving
scheduler = optim.lr_scheduler.ReduceLROnPlateau(
    optimizer, mode="max", factor=LR_DECAY, patience=2
)

# ╔══════════════════════════════════════════════════════════════╗
# ║  CELL 8 — Training & Validation Loop                        ║
# ╚══════════════════════════════════════════════════════════════╝

def train_one_epoch(model, loader, criterion, optimizer):
    model.train()
    running_loss, correct, total = 0.0, 0, 0

    for images, labels in tqdm(loader, desc="  Train", leave=False):
        images, labels = images.to(DEVICE), labels.to(DEVICE)

        optimizer.zero_grad()
        outputs = model(images)
        loss    = criterion(outputs, labels)
        loss.backward()
        optimizer.step()

        running_loss += loss.item() * images.size(0)
        preds         = outputs.argmax(dim=1)
        correct      += (preds == labels).sum().item()
        total        += labels.size(0)

    epoch_loss = running_loss / total
    epoch_acc  = correct / total
    return epoch_loss, epoch_acc


def validate(model, loader, criterion):
    model.eval()
    running_loss, all_preds, all_labels = 0.0, [], []

    with torch.no_grad():
        for images, labels in tqdm(loader, desc="  Val  ", leave=False):
            images, labels = images.to(DEVICE), labels.to(DEVICE)
            outputs        = model(images)
            loss           = criterion(outputs, labels)

            running_loss  += loss.item() * images.size(0)
            preds          = outputs.argmax(dim=1)
            all_preds.extend(preds.cpu().numpy())
            all_labels.extend(labels.cpu().numpy())

    epoch_loss = running_loss / len(all_labels)
    epoch_acc  = accuracy_score(all_labels, all_preds)
    epoch_f1   = f1_score(all_labels, all_preds, average="weighted")
    return epoch_loss, epoch_acc, epoch_f1


# ── Training loop ────────────────────────────────────────────────
best_val_acc    = 0.0
patience_count  = 0
history         = {"train_loss": [], "train_acc": [], "val_loss": [], "val_acc": [], "val_f1": []}

print("\n🚀 Starting Training...\n")

for epoch in range(1, NUM_EPOCHS + 1):
    t0 = time.time()

    train_loss, train_acc = train_one_epoch(model, train_loader, criterion, optimizer)
    val_loss, val_acc, val_f1 = validate(model, val_loader, criterion)

    scheduler.step(val_acc)

    elapsed = time.time() - t0
    print(f"Epoch [{epoch:02d}/{NUM_EPOCHS}]  "
          f"Train Loss: {train_loss:.4f}  Train Acc: {train_acc:.4f}  |  "
          f"Val Loss: {val_loss:.4f}  Val Acc: {val_acc:.4f}  F1: {val_f1:.4f}  "
          f"({elapsed:.1f}s)")

    history["train_loss"].append(train_loss)
    history["train_acc"].append(train_acc)
    history["val_loss"].append(val_loss)
    history["val_acc"].append(val_acc)
    history["val_f1"].append(val_f1)

    # Save best model
    if val_acc > best_val_acc:
        best_val_acc   = val_acc
        patience_count = 0
        torch.save(model.state_dict(), CHECKPOINT)
        print(f"   💾 Saved best model  (val_acc={best_val_acc:.4f})")
    else:
        patience_count += 1
        if patience_count >= PATIENCE:
            print(f"\n⏹  Early stopping triggered after {epoch} epochs (no improvement for {PATIENCE} epochs).")
            break

print(f"\n✅ Training complete. Best Val Accuracy: {best_val_acc:.4f}")

# ╔══════════════════════════════════════════════════════════════╗
# ║  CELL 9 — Plot Training Curves (optional, needs matplotlib) ║
# ╚══════════════════════════════════════════════════════════════╗

try:
    import matplotlib.pyplot as plt

    fig, axes = plt.subplots(1, 3, figsize=(16, 4))
    epochs_ran = range(1, len(history["train_loss"]) + 1)

    axes[0].plot(epochs_ran, history["train_loss"], label="Train")
    axes[0].plot(epochs_ran, history["val_loss"],   label="Val")
    axes[0].set_title("Loss"); axes[0].legend(); axes[0].set_xlabel("Epoch")

    axes[1].plot(epochs_ran, history["train_acc"], label="Train")
    axes[1].plot(epochs_ran, history["val_acc"],   label="Val")
    axes[1].set_title("Accuracy"); axes[1].legend(); axes[1].set_xlabel("Epoch")

    axes[2].plot(epochs_ran, history["val_f1"])
    axes[2].set_title("Val F1-Score"); axes[2].set_xlabel("Epoch")

    plt.tight_layout()
    plt.savefig("/content/training_curves.png", dpi=100)
    plt.show()
    print("📊 Training curves saved to /content/training_curves.png")
except Exception as e:
    print(f"(Plot skipped: {e})")

# ╔═══════════════════════════════════════════════╗
# ║  CELL 10 — Evaluate Best Model on Validation Set            ║
# ╚═══════════════════════════════════════════════╝

# Class names — adjust if your label encoding differs
CLASS_NAMES = [
    "AnnualCrop", "Forest", "HerbaceousVegetation", "Highway",
    "Industrial", "Pasture" # Removed "PermanentCrop", "Residential", "River", "SeaLake" as they are not found in the dataset
]

# Load best weights
model.load_state_dict(torch.load(CHECKPOINT, map_location=DEVICE))
model.eval()

_, final_val_acc, final_val_f1 = validate(model, val_loader, criterion)
print(f"\n┐ Final Val Accuracy : {final_val_acc:.4f}")
print(f"   Final Val F1-Score : {final_val_f1:.4f}")

# Detailed per-class report
model.eval()
all_preds, all_labels = [], []
with torch.no_grad():
    for images, labels in val_loader:
        images = images.to(DEVICE)
        preds  = model(images).argmax(dim=1).cpu().numpy()
        all_preds.extend(preds)
        all_labels.extend(labels.numpy())

print("\n│ Classification Report:")
print(classification_report(all_labels, all_preds, target_names=CLASS_NAMES))

# ╔══════════════════════════════════════════════════════════════╗
# ║  CELL 11 — Generate Submission File                         ║
# ╚══════════════════════════════════════════════════════════════╝

model.eval()
predictions, image_ids = [], []

with torch.no_grad():
    for images, ids in tqdm(test_loader, desc="Predicting test set"):
        images = images.to(DEVICE)
        preds  = model(images).argmax(dim=1).cpu().numpy()
        predictions.extend(preds)
        image_ids.extend(ids)

submission = pd.DataFrame({"image_id": image_ids, "label": predictions})
submission.to_csv(OUTPUT_CSV, index=False)

print(f"\n✅ Submission saved → {OUTPUT_CSV}")
print(submission.head(10))
print(f"\nLabel distribution:\n{submission['label'].value_counts().sort_index()}")

# ╔══════════════════════════════════════════════════════════════╗
# ║  CELL 12 — (Optional) Copy outputs back to Drive            ║
# ╚══════════════════════════════════════════════════════════════╗
# import shutil
# shutil.copy(OUTPUT_CSV,  "/content/drive/MyDrive/EuroSAT_Project/submission.csv")
# shutil.copy(CHECKPOINT,  "/content/drive/MyDrive/EuroSAT_Project/best_model.pth")
# print("📤 Files copied to Google Drive.")

# ╔══════════════════════════════════════════════════════════════╗
# ║  CELL 13 — (Optional) TTA — Test-Time Augmentation          ║
# ║  Run this INSTEAD of Cell 11 for a small accuracy boost     ║
# ╚══════════════════════════════════════════════════════════════╝

def predict_with_tta(model, dataset_dir, csv_path, transform, n_aug=5):
    """
    Average predictions over n_aug augmented versions of each test image.
    Uses the same train_transforms for augmentation.
    """
    tta_transform = transforms.Compose([
        transforms.Resize((IMG_SIZE, IMG_SIZE)),
        transforms.RandomHorizontalFlip(),
        transforms.RandomRotation(10),
        transforms.ToTensor(),
        transforms.Normalize(MEAN, STD),
    ])

    df = pd.read_csv(csv_path)
    df.columns = [c.strip().lower() for c in df.columns]
    img_col = "image_id" if "image_id" in df.columns else "filename"

    model.eval()
    all_preds, all_ids = [], []

    for _, row in tqdm(df.iterrows(), total=len(df), desc="TTA Predict"):
        img_path = os.path.join(dataset_dir, row[img_col])
        if not os.path.exists(img_path):
            img_path += ".jpg"

        image = Image.open(img_path).convert("RGB")
        logits = torch.zeros(NUM_CLASSES).to(DEVICE)

        with torch.no_grad():
            # 1 pass with standard transform
            x = transform(image).unsqueeze(0).to(DEVICE)
            logits += model(x).squeeze(0)
            # n_aug-1 passes with augmentation
            for _ in range(n_aug - 1):
                x = tta_transform(image).unsqueeze(0).to(DEVICE)
                logits += model(x).squeeze(0)

        pred = logits.argmax().item()
        all_preds.append(pred)
        all_ids.append(row[img_col])

    return all_ids, all_preds


# Uncomment to use TTA:
# tta_ids, tta_preds = predict_with_tta(model, DATASET_DIR, TEST_CSV, val_transforms, n_aug=5)
# submission_tta = pd.DataFrame({"image_id": tta_ids, "label": tta_preds})
# submission_tta.to_csv("/content/submission_tta.csv", index=False)
# print("✅ TTA submission saved → /content/submission_tta.csv")

# New Cell A — Install Gradio
!pip install -q gradio

# Commented out IPython magic to ensure Python compatibility.
# %%writefile /content/app.py
# """
# app.py — EuroSAT Land Cover Classifier Demo
# =============================================
# Gradio demo app — connects to the model saved by eurosat_sol.py (your train file).
# 
# HOW TO RUN IN GOOGLE COLAB (add as a new cell AFTER your training cells):
# ─────────────────────────────────────────────────────────────────────────
#     # Step 1 — install gradio (once per session)
#     !pip install -q gradio
# 
#     # Step 2 — write this file to disk
#     %%writefile /content/app.py
#     <paste entire contents of this file here>
# 
#     # Step 3 — run it
#     !python /content/app.py
# 
# Then click the public link that appears (e.g. https://xxxx.gradio.live)
# """
# 
# # ── Imports ────────────────────────────────────────────────────────────────────
# import os
# import numpy as np
# from PIL import Image
# import torch
# import torch.nn as nn
# from torchvision import transforms, models
# import gradio as gr
# 
# # ╔══════════════════════════════════════════════════════════════════════════╗
# # ║  CONFIG  — must match your eurosat_sol.py settings exactly              ║
# # ╚══════════════════════════════════════════════════════════════════════════╝
# 
# MODEL_PATH  = "/content/best_model.pth"   # saved by CHECKPOINT in your train file
# NUM_CLASSES = 6                            # you set NUM_CLASSES = 6
# IMG_SIZE    = 224
# DEVICE      = torch.device("cuda" if torch.cuda.is_available() else "cpu")
# 
# # Order MUST match the label integers (0,1,2,3,4,5) in your CSVs
# CLASS_NAMES = [
#     "AnnualCrop",
#     "Forest",
#     "HerbaceousVegetation",
#     "Highway",
#     "Industrial",
#     "Pasture",
# ]
# 
# CLASS_EMOJI = {
#     "AnnualCrop"           : "🌾",
#     "Forest"               : "🌲",
#     "HerbaceousVegetation" : "🌿",
#     "Highway"              : "🛣️",
#     "Industrial"           : "🏭",
#     "Pasture"              : "🐄",
# }
# 
# CLASS_DESCRIPTIONS = {
#     "AnnualCrop"           : "Fields of crops harvested and replanted every year (e.g. wheat, corn, rice).",
#     "Forest"               : "Dense tree cover — both deciduous and evergreen woodland.",
#     "HerbaceousVegetation" : "Low-growing non-woody plants: grasslands, meadows, and scrubland.",
#     "Highway"              : "Major road infrastructure clearly visible from satellite altitude.",
#     "Industrial"           : "Factories, warehouses, power plants, and large commercial zones.",
#     "Pasture"              : "Open grazing land maintained for livestock farming.",
# }
# 
# MEAN = [0.485, 0.456, 0.406]
# STD  = [0.229, 0.224, 0.225]
# 
# 
# # ╔══════════════════════════════════════════════════════════════════════════╗
# # ║  Load Model  (same architecture as build_model() in your train file)   ║
# # ╚══════════════════════════════════════════════════════════════════════════╝
# 
# def load_model():
#     m = models.efficientnet_b0(weights=None)
#     in_features = m.classifier[1].in_features
#     m.classifier = nn.Sequential(
#         nn.Dropout(p=0.3, inplace=True),
#         nn.Linear(in_features, NUM_CLASSES),
#     )
#     if os.path.exists(MODEL_PATH):
#         m.load_state_dict(torch.load(MODEL_PATH, map_location=DEVICE))
#         print(f"✅ Loaded weights from {MODEL_PATH}")
#     else:
#         print(f"⚠️  {MODEL_PATH} not found — run your training cells first!")
#     m.eval()
#     return m.to(DEVICE)
# 
# 
# model = load_model()
# 
# infer_tf = transforms.Compose([
#     transforms.Resize((IMG_SIZE, IMG_SIZE)),
#     transforms.ToTensor(),
#     transforms.Normalize(MEAN, STD),
# ])
# 
# 
# # ╔══════════════════════════════════════════════════════════════════════════╗
# # ║  Prediction                                                             ║
# # ╚══════════════════════════════════════════════════════════════════════════╝
# 
# def predict(image):
#     if image is None:
#         return "Please upload an image.", {}, ""
# 
#     tensor = infer_tf(image.convert("RGB")).unsqueeze(0).to(DEVICE)
# 
#     with torch.no_grad():
#         probs = torch.softmax(model(tensor), dim=1).squeeze().cpu().numpy()
# 
#     top_idx   = int(np.argmax(probs))
#     top_class = CLASS_NAMES[top_idx]
#     top_conf  = float(probs[top_idx])
# 
#     sorted_idx = np.argsort(probs)[::-1]
#     conf_dict  = {
#         f"{CLASS_EMOJI[CLASS_NAMES[i]]}  {CLASS_NAMES[i]}": float(probs[i])
#         for i in sorted_idx
#     }
# 
#     label_str = f"{CLASS_EMOJI[top_class]}  {top_class}   ({top_conf*100:.1f}% confident)"
#     desc_str  = CLASS_DESCRIPTIONS[top_class]
# 
#     return label_str, conf_dict, desc_str
# 
# 
# # ╔══════════════════════════════════════════════════════════════════════════╗
# # ║  Gradio UI                                                              ║
# # ╚══════════════════════════════════════════════════════════════════════════╝
# 
# CSS = """
# @import url('https://fonts.googleapis.com/css2?family=IBM+Plex+Mono:wght@400;700&family=IBM+Plex+Sans:wght@300;400;600&display=swap');
# 
# body, .gradio-container {
#     background: #f5f0e8 !important;
#     font-family: 'IBM Plex Sans', sans-serif !important;
#     color: #1a1a2e !important;
# }
# #app-header {
#     background: #1a1a2e;
#     color: #f5f0e8;
#     padding: 2rem 2rem 1.5rem;
#     border-radius: 12px;
#     margin-bottom: 1.5rem;
# }
# #app-header h1 {
#     font-family: 'IBM Plex Mono', monospace;
#     font-size: 1.7rem;
#     margin: 0 0 0.4rem;
#     color: #e8c547;
#     letter-spacing: -0.3px;
# }
# #app-header p {
#     margin: 0;
#     font-size: 0.9rem;
#     color: #a0a8c0;
#     font-weight: 300;
# }
# .gr-panel, .gr-box, .gr-form {
#     background: #ffffff !important;
#     border: 1px solid #ddd8cc !important;
#     border-radius: 10px !important;
# }
# #classify-btn {
#     background: #1a1a2e !important;
#     color: #e8c547 !important;
#     border: none !important;
#     font-family: 'IBM Plex Mono', monospace !important;
#     font-size: 0.9rem !important;
#     border-radius: 8px !important;
#     letter-spacing: 0.5px !important;
#     transition: opacity 0.2s !important;
# }
# #classify-btn:hover { opacity: 0.85 !important; }
# #clear-btn {
#     background: #f5f0e8 !important;
#     border: 1px solid #ddd8cc !important;
#     color: #666 !important;
#     border-radius: 8px !important;
# }
# #pred-label textarea {
#     font-family: 'IBM Plex Mono', monospace !important;
#     font-size: 1.05rem !important;
#     font-weight: 700 !important;
#     color: #1a1a2e !important;
#     background: #f5f0e8 !important;
#     border: 1px solid #ddd8cc !important;
# }
# #desc-box textarea {
#     font-size: 0.88rem !important;
#     color: #555 !important;
#     font-style: italic;
#     background: #f5f0e8 !important;
#     border: 1px solid #ddd8cc !important;
# }
# .label-confidence-bar-fill {
#     background: linear-gradient(90deg, #1a1a2e, #4a4a8e) !important;
# }
# #footer {
#     text-align: center;
#     color: #999;
#     font-size: 0.78rem;
#     font-family: 'IBM Plex Mono', monospace;
#     padding: 1rem 0 0.3rem;
# }
# """
# 
# with gr.Blocks(css=CSS, title="EuroSAT Classifier") as demo:
# 
#     gr.HTML("""
#     <div id="app-header">
#         <h1>🛰️  EuroSAT Land Cover Classifier</h1>
#         <p>EfficientNet-B0 trained on Sentinel-2 satellite imagery &nbsp;·&nbsp; 6 land-cover classes</p>
#     </div>
#     """)
# 
#     with gr.Row():
#         with gr.Column(scale=1):
#             img_input = gr.Image(type="pil", label="Upload Satellite Image", height=300)
#             with gr.Row():
#                 btn_classify = gr.Button("🔍  Classify Image", elem_id="classify-btn", variant="primary")
#                 btn_clear    = gr.ClearButton([img_input], value="✕ Clear", elem_id="clear-btn")
#             gr.Markdown(
#                 "**Classes this model recognises:**\n\n" +
#                 "  ".join([f"{v} {k}" for k, v in CLASS_EMOJI.items()])
#             )
# 
#         with gr.Column(scale=1):
#             out_label = gr.Textbox(label="Prediction", interactive=False, elem_id="pred-label")
#             out_conf  = gr.Label(label="Confidence Scores", num_top_classes=6)
#             out_desc  = gr.Textbox(label="About this class", interactive=False,
#                                    lines=2, elem_id="desc-box")
# 
#     gr.HTML('<div id="footer">EfficientNet-B0 · EuroSAT · Sentinel-2 · Trained in Google Colab</div>')
# 
#     btn_classify.click(fn=predict, inputs=img_input,
#                        outputs=[out_label, out_conf, out_desc])
#     img_input.change(fn=predict, inputs=img_input,
#                      outputs=[out_label, out_conf, out_desc])
# 
# 
# if __name__ == "__main__":
#     demo.launch(
#         share=True,       # generates public link — required for Colab
#         debug=False,
#         show_error=True,
#     )

# New Cell C — Launch the app
!python /content/app.py